sudo: required
services:
  - docker

before_install:
   - docker build -t presleyomozuwa/docker-react-app -f Dockerfile.dev .

scripts:
   - docker run presleyomozuwa/docker-react-app npm run test -- -- coverage